// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFzmNCIV8G-M_pdrhGDQbjsIGMkTWZ2U',
    appId: '1:541556910628:web:97c4772e23bba388dcc6b1',
    messagingSenderId: '541556910628',
    projectId: 'indivio-edtech-70a85',
    authDomain: 'indivio-edtech-70a85.firebaseapp.com',
    storageBucket: 'indivio-edtech-70a85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPFzmNCIV8G-M_pdrhGDQbjsIGMkTWZ2U',
    appId: '1:541556910628:android:97c4772e23bba388dcc6b1',
    messagingSenderId: '541556910628',
    projectId: 'indivio-edtech-70a85',
    storageBucket: 'indivio-edtech-70a85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY69G7KcVm2tgurAlAU1JPJZcBIIJoQC8',
    appId: '1:541556910628:ios:2de9e0918c8865e5dcc6b1',
    messagingSenderId: '541556910628',
    projectId: 'indivio-edtech-70a85',
    storageBucket: 'indivio-edtech-70a85.firebasestorage.app',
    iosBundleId: 'com.indivio.indivio',
  );
}
